name: Update Go Modules

on:
  push:
    branches:
      - withoutRoot

jobs:
  update-go-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: 'withoutRoot'
      
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          check-latest: true
      
      - name: Run go get -u
        run: |
          go get -u ./...
          go mod tidy
          gofmt -w .
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update go modules with workflow" || echo "No changes to commit"
          git push origin withoutRoot