name: Go Build for Android

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.5'  # 指定 Go 版本
    - name: Build
      run: |
        mkdir ${{ github.workspace }}/bin
        # CGO_ENABLED=0 GOOS=android GOARCH=arm64 go build -o ${{ github.workspace }}/bin/merge_android main.go
        # CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o ${{ github.workspace }}/bin/merge_linux main.go
        CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o ${{ github.workspace }}/bin/merge main.go
    - name: isExist
      run: |
        pwd 
        ls -al ${{ github.workspace }}/bin
    - name: Get current date and time
      id: get_date
      run: |
        export TZ="Asia/Shanghai"  # 设置时区为东八
        echo "release_name=$(date +'%Y-%m-%d %H:%M:%S')"
        echo "release_name=$(date +'%Y年%m月%d日%H时%M分%S秒')" >> $GITHUB_ENV
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        #tag_name 是必须值
        tag_name: ${{ env.release_name }} # 使用手动输入的版本名称
        files: |
          # ${{ github.workspace }}/bin/merge_linux
          # ${{ github.workspace }}/bin/merge_android
          ${{ github.workspace }}/bin/merge
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub 提供的自动生成的 token
