name: Go Build and Release

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release version name (e.g., v1.0.0)'
        required: true
        default: 'latest'  # 默认值

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'  # 指定 Go 版本

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o merge main.go

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.release_name }}  # 使用手动输入的版本名称
        files: merge  # 指定要发布的文件
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub 提供的自动生成的 token
